version: "3.8"

services:
  golang-dev-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-dev-svc:latest
    container_name: golang-dev-svc
    restart: on-failure
    # env_file:
    #   - .env
    depends_on:
      - golang-db
    ports:
      - "8090:8090"
  
  golang-prod-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-prod-svc:latest
    container_name: golang-prod-svc
    restart: on-failure
    # env_file:
    #   - .env
    depends_on:
      - golang-db
    ports:
      - "8091:8090"

  golang-db:
    container_name: golang-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      # Mounting volumes from server to local directory
      - /home/titan/database-docker/mysql:/var/lib/mysql
